account/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import superuser, del_user, edit_user, accept_organizer, reject_organizer
from .views import logout, Login, Signup, ForgetPassword, Activate, ConsolidatedView,contactus

urlpatterns = [
    path('login', Login.as_view(), name='login'),
    path('signup', Signup.as_view(), name='signup'),
    path('contact', contactus, name='contactus'),
    path('logout', login_required(logout), name='logout'),
    path('activate/<uidb64>/<token>/', Activate.as_view(), name='activate'),
    path('forget-password/<uidb64>/<token>', ForgetPassword.as_view(), name='forget_password'),

    path('superuser/', login_required(superuser), name='superuser'),
    path('edit_user/<username>', login_required(edit_user), name='edit_user'),
    path('delete-user/<username>', login_required(del_user), name='delete_user'),

    path('consolidated-view-all', login_required(ConsolidatedView.as_view()), name='consolidated_view_all'),
    path('consolidated-view-username/<username>', login_required(ConsolidatedView.as_view()), name='consolidated_username'),
    path('accept_organizer/<int:id>/', accept_organizer, name='accept_organizer'),
    path('reject_organizer/<int:id>/', reject_organizer, name='reject_organizer'),
]

event/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import AddEvent, EventDetail, UpdateEvent, DeleteEvent, EventListView, showform, createform, updateform

urlpatterns = [
    path('', EventListView.as_view(), name='event_list'),
    path('add-event', login_required(AddEvent.as_view()), name='add_event'),
    path('<slug>/event-form/', login_required(showform), name='event_form'),
    path('<slug>/create-form/',login_required(createform), name='create_form'),
    path('<slug>/update-form/',login_required(updateform), name='update_form'),
    path('<slug>/event-detail', EventDetail.as_view(), name='event_detail'),
    path('<slug>/update-event', login_required(UpdateEvent.as_view()), name='update_event'),
    path('<slug>/delete/<timestamp>', login_required(DeleteEvent.as_view()), name='delete_event'),
]

eventlify/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from .router import router

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from .views import *

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_TITLE

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('event/', include(('event.urls', 'event'), namespace='event')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('registration/', include(('registration.urls', 'registration'), namespace='registration')),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('api/',include(router.urls)),


    # path('set', set_user),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import RegisterEvent, RegisterParticipantList, RegistrationDetail
from .views import EnrollmentReport, RegistrationReport, TransactionReport
from .views import payment_view, payment_success_view,ticket

urlpatterns = [
    path('<slug>/payment/', payment_view, name='payment'),
    path('<slug>/payment/success', payment_success_view, name='payment_success'),
    path('<slug>/ticket/', ticket, name='ticket'), #timestamp/
    path('<slug>/register-event', RegisterEvent.as_view(), name='register_event'),
    path('<slug>/participant-list', login_required(RegisterParticipantList.as_view()), name='participant_list'),
    path('<registration_id>/detail', login_required(RegistrationDetail.as_view()), name='registration_detail'),
    path('<slug>/print-enroll-list', login_required(EnrollmentReport.as_view()), name='print_enroll_list'),
    path('<slug>/print-organizer-list', login_required(RegistrationReport.as_view()), name='print_organizer_list'),
    path('<slug>/print-transaction-list', login_required(TransactionReport.as_view()), name='print_transaction_list'),
]

account/models.py
from django.db import models

# Create your models here.

account/views.py
from datetime import date

from django.conf import settings
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import TemplateView
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.shortcuts import get_object_or_404
from django.http import JsonResponse

from event.models import EventRecord
from eventlify.settings import BASE_URL
from registration.models import RegistrationRecord
from organizer.forms import organizerForm
from organizer.models import organizerRecord
from .forms import SignupForm, LoginForm, ResetPasswordForm, EditUserForm, EmailForm
from .tokens import account_activation_token, password_reset_token


# Create your views here.
def is_block(request, user):
    if not user.is_active and user.last_login:
        return True
    return False


def logout(request):
    auth.logout(request)
    return redirect('event:event_list')




class Login(TemplateView):
    template_name = 'login.html'

    def get(self, request, *args, **kwargs):
        form = LoginForm()
        form1 = EmailForm()
        request.session['head_name'] = 'login'
        return render(request, self.template_name, {'form': form, 'form1': form1})

    def post(self, request):
        try:
            form = LoginForm(request.POST)
            form1 = EmailForm(request.POST)
            status=''

            # Login Form
            if form.is_valid():
                email = form.cleaned_data['email']
                password = form.cleaned_data['password']
                user = authenticate(username=email.lower(), password=password)
                u = organizerRecord.objects.filter(Email=email)
                for i in u:
                    status = i.status
                
                if user is not None:
                    if is_block(request, user):
                        raise PermissionDenied('Your Account is blocked. Please Contact Us')
                    login(request, user)
                    if 'next' in request.POST:
                        return redirect(request.POST.get('next'))
                    if status == 'unverified':
                        messages.warning(request, 'You can add event after the admin approve')

                    return redirect("account:consolidated_view_all")
                else:
                    messages.error(request, "Your authentication information is incorrect. Please try again.")

            # Forget Password
            elif form1.is_valid():
                email = form1.cleaned_data['email1']
                user = User.objects.get(username=email.lower())
                if is_block(request, user):
                    raise PermissionDenied('Your Account is blocked. Please Contact Us')

                # Email Sending
                current_site = get_current_site(request)
                mail_subject = 'Password Reset link of your eventlify Account.'
                message = render_to_string('forget-password.txt', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': password_reset_token.make_token(user),
                    'email': settings.CONTACT_EMAIL,
                    'number': settings.CONTACT_NUMBER
                })
                email = EmailMessage(mail_subject, message, to=[user.email])
                email.send()

                messages.success(request, 'Password reset link has been sent to your registered E-mail Address')
                return redirect('event:event_list')
            else:
                messages.warning(request, 'Invalid Input. Please try again')

        except ObjectDoesNotExist:
            messages.error(request, 'Invalid Inputs. Please try again')
        except PermissionDenied as e:
            messages.error(request, e)
            return redirect('event:event_list')
        except Exception as e:
            messages.error(request, (str(e) + '. Please Contact Us'))

        form = LoginForm()
        form1 = EmailForm()
        return render(request, self.template_name, {'form': form, 'form1': form1})
    
    
# noinspection PyBroadException

def contactus(request):
    request.session['head_name'] = 'contactus'
    return render(request, "contactus.html")

class Signup(TemplateView):
    template_name = 'signup.html'

    def get(self, request):
        # Render the signup form
        request.session['head_name'] = 'signup'
        form = SignupForm()
        return render(request, self.template_name, {'form1': form})

    def post(self, request):
        try:
            form = SignupForm(request.POST)
            if form.is_valid():
                first_name = form.cleaned_data['first_name']
                last_name = form.cleaned_data['last_name']
                email = form.cleaned_data['email'].lower()
                password = form.cleaned_data['password']
                try:
                    user = User.objects.get(username=email)
                    if is_block(request, user):
                        raise PermissionDenied('Your Account is blocked. Please Contact Us')
                    user.first_name = first_name
                    user.last_name = last_name
                    user.set_password(password)
                    user.save()
                except ObjectDoesNotExist:
                    user = User.objects.create(username=email, email=email, password=password, first_name=first_name,
                                               last_name=last_name, is_active=False,is_staff=False)
                    
                    

                '''Begin Email Sending '''
                current_site = get_current_site(request)
                mail_subject = 'Action Required: Activate your eventlify account'
                message = render_to_string('acc_active_email.txt', {
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                    'email': settings.CONTACT_EMAIL,
                    'number': settings.CONTACT_NUMBER
                })
                email = EmailMessage(mail_subject, message, to=[user.email])
                email.send()
                '''End Email sending'''

                messages.success(request, 'Check your mail to complete registration')
                return redirect("account:login")
            else:
                messages.warning(request, 'Invalid Input. Please try again')
            
            return render(request, self.template_name, {'form1': form})

        except PermissionDenied as e:
            messages.error(request, e)
            return redirect('event:event_list')
        except Exception as e:
            messages.error(request, (str(e) + '. Please Contact Us'))
            return redirect("account:signup")


# noinspection PyBroadException
class Activate(TemplateView):
    template_name = 'activate.html'

    def get(self, request, *args, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(kwargs['uidb64']))
            user = User.objects.get(pk=uid)
            if account_activation_token.check_token(user, kwargs['token']):
                if is_block(request, user):
                    raise PermissionDenied('Your Account is blocked. Please Contact Us')

                form = organizerForm()
                return render(request, self.template_name, {'user': user, 'form': form})
            else:
                raise PermissionDenied('Activation link is invalid! Please SignUp Again or Contact Us')

        except PermissionDenied as e:
            messages.error(request, e)
            return redirect('event:event_list')
        except Exception as e:
            messages.error(request, (str(e) + '. Please Contact Us'))
            return redirect("account:signup")

    def post(self, request, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(kwargs['uidb64']))
            user = User.objects.get(pk=uid)
            if account_activation_token.check_token(user, kwargs['token']):
                if is_block(request, user):
                    raise PermissionDenied('Your Account is blocked. Please Contact Us')

                form = organizerForm(request.POST,request.FILES)
                
                if form.is_valid():
                    temp = form.save(commit=False)
                    temp.user = user
                    temp.save()
                    user.is_active = False
                    user.save()
                    auth.login(request, user)
                    messages.success(request, 'Thank you for Registration')
                    messages.warning(request, 'You can add event after the admin approve')
                    return redirect("event:event_list")
                else:
                    messages.warning(request, 'Invalid Input')
                    return render(request, self.template_name, {'user': user, 'form': form})
            else:
                raise PermissionDenied('Activation link is invalid! Please SignUp Again or Contact Us')

        except PermissionDenied as e:
            messages.error(request, e)
            return redirect('event:event_list')
        except Exception as e:
            messages.error(request, (str(e) + '. Please Contact Us'))
            return redirect("account:signup")

account/templates/activate.html
{% extends "base.html" %}{% block head_title %}Account Activation | {{ block.super }}{% endblock %}{% block content %}
    <main role="main" class="container col-xl-4 col-lg-5 col-md-6 p-4 mt-md-4 mt-2 mb-5" style="background-color: #f7f5f5;box-shadow: 0 0 5px 5px #d4d2cf;border-radius: 5px">
        <h3 class="text-center pb-3">Fill your Personal Detail</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            <div class="row">
                <div class="col-md-6 mb-4">
                    <label for="first_name">First Name</label><input id="first_name" type="text" class="form-control" value="{{ user.first_name }}" disabled>
                    <input type="hidden" name="Fname" value="{{ user.first_name }}">
                </div>
                <div class="col-md-6 mb-4">
                    <label for="last_name">Last Name</label><input id="last_name" type="text" class="form-control" value="{{ user.last_name }}" disabled>
                    <input type="hidden" name="Lname" value="{{ user.last_name }}">
                    
                <input type="hidden" name="Email" value="{{ user.email }}">
                </div>
            </div>
            <div class="mb-4">
                <label for="email">Email</label><input id="email" type="email" class="form-control" value="{{ user.email }}" disabled>{{ form.email }}
            </div>
            <div class="row">
                <div class="col-md-6 mb-4">
                    <label>Mobile Number</label>
                    {{ form.Mobile }}<span style="color:red;">{{ form.Mobile.errors }}</span>
                </div>
                <div class="col-md-6 mb-4">
                    <label>Date of Birth</label>{{ form.Dob }}<span style="color:red;">{{ form.Dob.errors }}</span>
                </div>
            </div>
            <div class="mb-4"><label>Address</label><br>{{ form.Address }}</div>
            <div class="row">
                <div class="col-md-4 mb-4"><label>ID Type</label>{{ form.Id_type }}</div>
                <div class="col-md-4 mb-4"><label>ID Upload</label>{{ form.Id_file }}</div>
            </div>
            <button type="submit" class="btn btn-success btn-block mb-4">Activate Account</button>
            <a href="{% url 'home' %}" class="btn btn-outline-danger btn-block">Go to Home Page</a>
        </form>
    </main>
    <script>
        function dob() {
            var date = new Date();
            var dd = date.getDate();
            var mm = date.getMonth() + 1;
            var yyyy = date.getFullYear();
      
            //Add a zero if one Digit (eg: 05,09)
            if (dd < 10) {
              dd = "0" + dd;
            }
      
            //Add a zero if one Digit (eg: 05,09)
            if (mm < 10) {
              mm = "0" + mm;
            }
      
            minYear = yyyy - 80; //Calculate Minimun Age (<80)
            maxYear = yyyy - 18; //Calculate Maximum Age (>18)
      
            var min = minYear + "-" + mm + "-" + dd;
            var max = maxYear + "-" + mm + "-" + dd;
      
            document.getElementById("start").setAttribute("min", min);
            document.getElementById("start").setAttribute("max", max);
          };
    </script>
    
    {% endblock %}{% block script %}{% endblock %}

account/templates/consolidated_view.html
{% extends "base.html" %}
{% load staticfiles %}
{% block head_title%}
Consolidated View | {{ block.super }}
{% endblock %}
{% block css %}{% endblock%}
{% block content %}
<main role="main" class="container p-4 mt-md-4 mt-2 mb-5">
  <div class="card-deck my-4">
    {% if user.is_staff or user.is_superuser %}
    {% for event in event_list %}
    {% if not event.deleted %}
    <div class="card mb-4 shadow-sm" style="height: 25rem">
      <div
        style="color: black"
        class="card-header btn-toolbar justify-content-between"
      >
        <span class="font-weight-normal text-capitalize"
          >{{ event.types }}</span
        >
        {% if now <= event.registration_end %}<span class="text-success"
          >Active</span
        >
        {% else %}<span class="text-danger">Not Active</span>
        {% endif %}
      </div>
      <div class="card-body" style="color: black">
        <p>
          Event Name:
          <a href="{% url 'event:event_detail' event.slug %}"
            >{{ event.event_title }}</a
          ><br />
          Event Code:
          <a href="{% url 'event:event_detail' event.slug %}">{{ event.id }}</a
          ><br />
          Event Date:
          <span class="text-danger"
            >{{ event.event_start_date|date:"F d, Y" }}</span
          ><br />
          {% if user.is_superuser %}
          organizer: 
          <a href="{% url 'account:consolidated_username' event.user %}">
              {{event.user}}
            </a>
            {% endif %}
        </p>
        <p>No. of people Registered : {{ event.event_booked }}</p>
        <div class="pt-2 btn-toolbar justify-content-between">
          {% comment %}
          <a href="{% url 'registration:participant_list' event.slug %}"
            >Participant List</a
          >
            
          {% endcomment %}
          <a href="{% url 'registration:print_organizer_list' event.slug %}"
            >Registration Report</a
          >
        </div>
        <div class="pt-2 btn-toolbar justify-content-between">
          <a href="{% url 'registration:print_transaction_list' event.slug %}"
            >Transaction Report</a
          >
          <a href="{% url 'registration:print_enroll_list' event.slug %}"
            >Enrollment Report</a
          >
        </div>
      </div>
      <hr />
      <div class="pb-3 px-3 btn-toolbar justify-content-between">
        <a
          href="{% url 'event:update_event' slug=event.slug %}"
          class="btn btn-outline-primary btn-sm px-4"
          >Update</a
        >
        <a
          href="{% url 'event:delete_event' slug=event.slug timestamp=event.timestamp %}"
          class="btn btn-outline-danger btn-sm px-4"
          onclick="return confirm('Are you sure to Delete {{ event.event_name }} event?')"
          >Delete</a
        >
      </div>
    </div>
    {% endif %}
    {% endfor %}
    {% if not event_list %}
    <span class="text-danger">No Event Yet. Please create a Event</span>{% endif%}
    {% else %} 
    {% for reg in event_list %}
    <div class="card mb-4 shadow-sm">
      <div class="card-header btn-toolbar justify-content-between">
        <span class="font-weight-normal text-capitalize"
          >{{ reg.event.type }}</span
        >
        {% if now <= reg.event.registration_end %}<span class="text-success"
          >Active</span
        >
        {% else %}<span class="text-danger">Not Active</span>{% endif %}
      </div>
      <div class="card-body">
        <p>
          Event Name:
          <a href="{% url 'event:event_detail' reg.event %}"
            >{{ reg.event.event_name }}</a
          ><br />
          Event Code:
          <a href="{% url 'event:event_detail' reg.event %}">{{ reg.event }}</a
          ><br />
          Event Date:
          <span class="text-danger"
            >{{ reg.event.event_date|date:"F d, Y" }}</span
          ><br />
          Trainer: {{ reg.event.user.first_name }} {{ reg.event.user.last_name
          }}
        </p>
      </div>
      <hr />
      <div class="pb-3 px-3 btn-toolbar justify-content-between">
        <a
          href="{% url 'event:event_detail' reg.event %}"
          class="btn btn-outline-primary btn-sm px-4"
          >Detail</a
        >
        <a href="" class="btn btn-outline-danger btn-sm px-4">Feedback</a>
      </div>
    </div>
    {% endfor %}{% endif %}
  </div>
</main>
    {% endblock %}
    {% block script %}{% endblock %}

account/templates/contactus.html
{% extends "base.html" %}{% load staticfiles %}{% block head_title %}Contactus {% endblock %} {% block css %}{% endblock %}{% block content %}
    <main
      role="main"
      class="container col-xl-4 col-lg-5 col-md-6 p-4 mt-md-4 mt-2 mb-5"
      style="
        background-color: #f7f5f5;
        box-shadow: 0 0 5px 5px #d4d2cf;
        border-radius: 5px;
      "
    >
      <h3 class="text-center pb-3">Contact us</h3>
      <form id="signupForm" method="post">
        {% csrf_token %}
        <div class="row">
          <div class="col-md-6 mb-4">
            <label>Email:</label><a href="mailto:connect.Eventlify@gmail.com">connect.Eventlify@gmail.com</a>
            
          </div>
          
    </main>
    {% endblock %}{% block script %}
    
    {% endblock %}
    

account/templates/edit_user.html
{% extends "base.html" %}{% load staticfiles %}{% block head_title %}Update Account | {{ block.super }}{% endblock %}
{% block css %}{% endblock %}
{% block content %}
    <main role="main" class="container col-md-6 bg-white">
        <div class="px-md-3 px-2 pt-4 pb-5">
            <div style="text-align: center">
                <h3>Update Account</h3>
            </div>
            <form action="" method="post" class="px-md-2">{% csrf_token %}
                <div class="mb-3">
                    <label>Email</label>{{ form.email }}{{ form.email.errors }}
                </div>
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label>First Name</label>{{ form.first_name }}{{ form.first_name.errors }}
                    </div>
                    <div class="col-md-6 mb-3">
                        <label>Last Name</label>{{ form.last_name }}{{ form.last_name.errors }}
                    </div>
                </div>
                <div class="mb-3">
                    <label>Password</label>{{ form.password }}{{ form.password.errors }}</div>
                <div class="mb-3" style="font-size: 14px">
                    <li>Use at least one lowercase and uppercase letter, one numeral, one symbol and 8 character
                    </li>
                    <li>Your password can&#39;t be a commonly used password.</li>
                    <li>Your password can&#39;t be entirely numeric.</li>
                    <li>Your password can&#39;t be too similar to your other personal information.</li>
                </div>
                <div class="mb-3">
                    <label>Confirm Password</label>{{ form.confirm_password }}{{ form.confirm_password.errors }}
                </div>
                <div class="py-2 clearfix">
                    <button type="submit" class="btn btn-outline-success btn-block mb-2">Submit</button>
                    <button type="reset" class="btn btn-outline-danger btn-block mb-2">Reset</button>
                </div>
            </form>
        </div>
    </main>
{% endblock %}

account/templates/login.html
{% extends "base.html" %}{% load staticfiles %}{% block head_title %}Login{% endblock %} {% block css %}{% endblock %}{% block content %}
<main
  role="main"
  class="container col-xl-3 col-lg-5 col-md-6 p-4 mt-md-4 mt-2 mb-5"
  style="
    background-color: #f7f5f5;
    box-shadow: 0 0 5px 5px #d4d2cf;
    border-radius: 5px;
  "
>
  <h3 class="text-center pb-3">Login To Your Account</h3>
  <form method="post" id="loginForm">
    {% csrf_token %}
    <div class="mb-4"><label>Email</label>{{ form.email }}</div>
    <div class="mb-4"><label>Password</label>{{ form.password }}</div>
    {% if request.GET.next %}<input
      type="hidden"
      name="next"
      value="{{ request.GET.next }}"
    />{% endif %}
    <button type="submit" class="btn btn-success btn-block mb-3">Login</button>
  </form>
  <div class="btn-toolbar justify-content-end">
    <button
      class="btn btn-sm btn-outline-info mb-3"
      data-toggle="modal"
      data-target="#myModal2"
    >
      Forget Password
    </button>
  </div>
  <a href="{% url 'account:signup' %}" class="btn btn-outline-danger btn-block"
    >Signup</a
  >
</main>
<div
  class="modal fade"
  id="myModal2"
  tabindex="-1"
  role="dialog"
  aria-labelledby="myModalLabel2"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title px-1" id="myModalLabel2">Forget Password</h4>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body px-4">
        <p>Enter Your Registered Email Id</p>
        <p>We will send you a Password Reset Link</p>
        <form class="row pl-3" method="post" id="forgetPasswordForm">
          {% csrf_token %}{{ form1.email1 }}
          <input
            type="submit"
            class="btn col-3 btn-outline-danger mb-2 float-right"
          />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}{% block script %}
<script>
  $("#loginForm").submit(function (e) {
    e.preventDefault();
    this.submit();
  });
</script>
<script>
  $("#forgetPasswordForm").submit(function (e) {
    e.preventDefault();
    this.submit();
  });
</script>
{% endblock %}

account/templates/reset-password.html
{% extends "base.html" %}{% load staticfiles %}{% block head_title %}Forget
Password | {{ block.super }}{% endblock %} {% block css %}{% endblock %}
{% block content %}
<main
  role="main"
  class="container col-xl-3 col-lg-5 col-md-6 p-4 mt-md-4 mt-2 mb-5"
  style="
    background-color: #f7f5f5;
    box-shadow: 0 0 5px 5px #d4d2cf;
    border-radius: 5px;
  "
>
  <h3 class="text-center pb-3">Change Your Password</h3>
  <form method="post">
    {% csrf_token %}
    <div class="mb-4">
      <label>Password</label>{{ form.password }}<span style="color: red"
        >{{ form1.password.errors }}</span
      >
    </div>
    <div class="mb-4">
      <label>Re-Enter Password</label>{{ form.confirm_password }}<span
        style="color: red"
        >{{ form1.confirm_password.errors }}</span
      >
    </div>
    <button type="submit" class="btn btn-success btn-block mb-4">
      Update Password
    </button>
  </form>
  <a href="{% url 'account:login' %}" class="btn btn-outline-info btn-block"
    >Go to Login</a
  >
</main>
{% block script %}{% endblock script %}
{% endblock %}

account/templates/signup.html
{% extends "base.html" %}{% load staticfiles %}{% block head_title %}Signup{% endblock %} {% block css %}{% endblock %}{% block content %}
<main
  role="main"
  class="container col-xl-4 col-lg-5 col-md-6 p-4 mt-md-4 mt-2 mb-5"
  style="
    background-color: #f7f5f5;
    box-shadow: 0 0 5px 5px #d4d2cf;
    border-radius: 5px;
  "
>
  <h3 class="text-center pb-3">Create Account</h3>
  <form id="signupForm" method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-md-6 mb-4">
        <label>First Name</label>{{ form1.first_name }}<span style="color: red"
          >{{ form1.first_name.errors }}</span
        >
      </div>
      <div class="col-md-6 mb-4">
        <label>Last Name</label>{{ form1.last_name }}<span style="color: red"
          >{{ form1.last_name.errors }}</span
        >
      </div>
    </div>
    <div class="mb-4">
      <label>Email</label>{{ form1.email }}<span style="color: red"
        >{{ form1.email.errors }}</span
      >
    </div>
    <div class="mb-4">
      <label>Password</label>{{ form1.password }}<span style="color: red"
        >{{ form1.password.errors }}</span
      >
    </div>
    <div class="mb-3" style="font-size: 14px">
      <li>
        Use at least one lowercase and uppercase letter, one numeral, one symbol
        and 8 character
      </li>
      <li>Your password can't be a commonly used password.</li>
      <li>
        Your password can't be too similar to your other personal information.
      </li>
    </div>
    <div class="mb-4">
      <label>Re-Enter Password</label>{{ form1.confirm_password }}
      <span style="color: red">{{ form1.confirm_password.errors }}</span>
    </div>
    <button type="submit" class="btn btn-success btn-block mb-4">Signup</button>
  </form>
  <a href="{% url 'account:login' %}" class="btn btn-outline-info btn-block"
    >Login</a
  >
</main>
{% endblock %}{% block script %}
<script>
  $("#signupForm").submit(function (e) {
    e.preventDefault();
    this.submit();
  });
</script>
{% endblock %}