event/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import AddEvent, EventDetail, UpdateEvent, DeleteEvent, EventListView, showform, createform, updateform

urlpatterns = [
    path('', EventListView.as_view(), name='event_list'),
    path('add-event', login_required(AddEvent.as_view()), name='add_event'),
    path('<slug>/event-form/', login_required(showform), name='event_form'),
    path('<slug>/create-form/',login_required(createform), name='create_form'),
    path('<slug>/update-form/',login_required(updateform), name='update_form'),
    path('<slug>/event-detail', EventDetail.as_view(), name='event_detail'),
    path('<slug>/update-event', login_required(UpdateEvent.as_view()), name='update_event'),
    path('<slug>/delete/<timestamp>', login_required(DeleteEvent.as_view()), name='delete_event'),
]

eventlify/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from .router import router

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from .views import *

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_TITLE

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('event/', include(('event.urls', 'event'), namespace='event')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('registration/', include(('registration.urls', 'registration'), namespace='registration')),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('api/',include(router.urls)),


    # path('set', set_user),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone
from django.utils.text import slugify

class EventRecord(models.Model):
    slug = models.SlugField(unique=True,null=True,blank=True)
    types = models.CharField(max_length=110, blank=True,default='')
    event_title = models.CharField(max_length=110, null=True, blank=True)
    event_subtitle = models.CharField(max_length=110, null=True, blank=True)
    fees = models.FloatField(default=0)
    about = RichTextUploadingField(null=True, blank=True)
    event_start_date = models.DateField(null=True, blank=True)
    event_end_date = models.DateField(null=True, blank=True)
    event_start_time = models.TimeField(null=True, blank=True) 
    event_end_time = models.TimeField(null=True, blank=True)
    venue = models.CharField(max_length=150, null=True, blank=True)
    state = models.CharField(max_length=150, null=True, blank=True)
    country = models.CharField(max_length=150, null=True, blank=True)
    visibility = models.CharField(max_length=50, null=True, blank=True)
    platform = models.CharField(max_length=50, null=True, blank=True)
    registration_start = models.DateField(null=True, blank=True)
    registration_end = models.DateField(null=True, blank=True)
    no_of_tickets = models.IntegerField(null=True, blank=True)
    category = models.CharField(max_length=50, null=True, blank=True)
    subcategory = models.CharField(max_length=50, null=True, blank=True)
    website = models.CharField(max_length=50, null=True, blank=True)
    facebook = models.CharField(max_length=50, null=True, blank=True)
    instagram = models.CharField(max_length=50, null=True, blank=True)
    youtube = models.CharField(max_length=50, null=True, blank=True)
    poster = models.FileField(default="")
    event_booked = models.IntegerField(default=0)
    registration_open = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    deleted = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.registration_start and self.registration_end:
            now = timezone.now().date()
            if now >= self.registration_start and now <= self.registration_end:
                self.registration_open = True
            else:
                self.registration_open = False

        if not self.slug:
            self.slug = self.get_unique_slug(self.event_title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.event_title

    def get_unique_slug(self, title):
        timestamp = timezone.now().strftime('%Y%m%d%H%M%S')
        slug = slugify(f"{title}-{timestamp}")
        unique_slug = slug
        num = 1
        while EventRecord.objects.filter(slug=unique_slug).exists():
            unique_slug = f"{slug}-{num}"
            num += 1
        return unique_slug




OPTION = [
    ('text', 'Text'),
    ('number', 'Number'),
    ('email', 'Email'),
    ('textarea', 'Textarea')
]


class Client(models.Model):
    event = models.ForeignKey(EventRecord, on_delete=models.CASCADE)
    label = models.CharField(max_length=200,null=True)
    type = models.CharField(max_length=20, choices=OPTION,null=True)
    organizer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    

    def __str__(self):
        return self.label


class Answer(models.Model):
    email = models.EmailField(default='')
    event = models.ForeignKey(EventRecord, null=True, on_delete=models.CASCADE, blank=True)
    question = models.ForeignKey(Client, null=True, on_delete=models.CASCADE)
    response = models.CharField(max_length=200,null=True)

    def __str__(self):
            return self.email

class DataList(models.Model):
    place = models.CharField(max_length=50)
    number = models.IntegerField()

    def __str__(self):
        return self.place

event/views.py
from datetime import date
from django.db.models import Q

from django.contrib import messages
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.forms import modelformset_factory
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import TemplateView
from organizer.models import organizerRecord
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseRedirect


from registration.models import RegistrationRecord
from .forms import AnswerForm, EventForm,ClientForm
from .models import Answer, EventRecord,Client
from eventlify.settings import BASE_URL



def createform(request,*args, **kwargs):
    if(request.method == "POST"):
        form = ClientForm(request.POST)
        obj = EventRecord.objects.get(slug=kwargs['slug'])
        if form.is_valid():
            temp = form.save(commit=False)
            temp.organizer = request.user
            temp.event = obj
            temp.save()
            
            messages.success(request, 'Submitted Successfully')
            context = {"form": temp}
            return render(request, "form/contact.html",context)
    
    else:
        try:
            obj = EventRecord.objects.get(slug=kwargs['slug'])
            form = ClientForm()
            context = {'form': form,'slug':obj.slug}
            return render(request, "form/form.html", context)
        except Exception:
            return redirect('event:event_list')
        


def answerform(request,*args, **kwargs):
    if(request.method == "POST"):
        form = AnswerForm(request.POST)
        obj = EventRecord.objects.get(slug=kwargs['slug'])
        if form.is_valid():
            temp = form.save(commit=False)
            temp.user = request.user
            temp.event = obj
            temp.save()
            messages.success(request, 'Submitted Successfully')
            context = {"contact": temp}
            return render(request, "form/contact.html",context)
    
    else:
        try:
            obj = EventRecord.objects.get(slug=kwargs['slug'])
            form = AnswerForm()
            context = {'form': form,'slug':obj.slug}
            return render(request, "form/form.html", context)
        except Exception:
            return redirect('event:event_list')
        

def updateform(request, *args, **kwargs):
    obj = get_object_or_404(EventRecord, slug=kwargs['slug'])
    clt_queryset = Client.objects.filter(event=obj)
    
    if request.method == "POST":
        ClientFormSet = modelformset_factory(Client, form=ClientForm, extra=0)
        formset = ClientFormSet(request.POST, queryset=clt_queryset)
        if formset.is_valid():
            formset.save()
            messages.success(request, 'Form Updated')
            context = {"formupdate": formset}
            return render(request, "form/contact.html", context)
        else:
            messages.error(request, 'Invalid Input')
    else:
        formset = ClientForm()

    context = {'formset': formset, 'slug': obj.slug}
    return render(request, "form/form.html", context)


def showform(request, *args, **kwargs):
    obj = EventRecord.objects.get(slug=kwargs['slug'])
    clt = Client.objects.filter(event=obj)
    
    if clt:
        ClientFormSet = modelformset_factory(Client, form=ClientForm, extra=0)
        formset = ClientFormSet(queryset=clt)
    else:
        formset = ClientForm()
    
    context = {'formset': formset, 'slug': obj.slug, 'client': clt}
    return render(request, "form/index.html", context)

    

# Create your views here.
class EventListView(TemplateView):
    template_name = 'event-list.html'

    def get(self, request, *args, **kwargs):
        request.session['head_name'] = 'event'
        event_list = EventRecord.objects.all().order_by('-event_start_date')
        form = EventForm()
        category = request.GET.get('category')
        platform = request.GET.get('platform')
        search_query = request.GET.get('search')
        if search_query:
            event_list = event_list.filter(
                Q(event_title__icontains=search_query) |
                Q(about__icontains=search_query)
            )

        # Apply category filter if parameter is provided
        if category != None:
            event_list = event_list.filter(category=category)
        if platform != None:
            event_list = event_list.filter(platform=platform)
        
        now = date.today()
        for i in event_list:
            if not now <= i.registration_end:
                i.registration_open = False
                i.save(update_fields=['registration_open'])

        return render(request, self.template_name, {'event_list': event_list,'form': form})


# noinspection PyBroadException
class EventDetail(TemplateView):
    template_name = 'event_detail.html'

    def get(self, request, *args, **kwargs):
        try:
            owner = False
            registered = True
            obj = EventRecord.objects.get(slug=kwargs['slug'])
            base_url = BASE_URL
            
            if obj.user == request.user or request.user.is_superuser:
                owner = True
            else:
                try:
                    RegistrationRecord.objects.get(user=request.user, event=obj)
                except Exception:
                    registered = False
            print(obj.event_booked)
            return render(request, self.template_name,
                          {'obj': obj, 
                           'owner': owner, 
                           'registered': registered, 
                           'now': date.today(),
                           'base':base_url})
        except ObjectDoesNotExist:
            messages.error(request, 'Event Not found')
            return redirect('event:event_list')


    # def post(self, request):
    #     if True:
    #         if request.user.is_staff:
    #             form = EventForm(request.POST, request.FILES)
    #             if form.is_valid():
    #                 temp = form.save(commit=False)
    #                 temp.user = request.user
    #                 form.save()
    #                 messages.success(request, 'Event Added')
    #                 return redirect('event:event_detail', slug=temp.slug)
    #             else:
    #                 messages.error(request, 'Invalid Input')
    #         else:
    #             raise PermissionDenied
    #         return render(request, self.template_name, {'form': form,'base':BASE_URL})
    
# noinspection PyBroadException
class AddEvent(TemplateView):
    template_name = 'add_update_event.html'
    def get(self, request, *args, **kwargs):
        request.session['head_name'] = 'add_event'
        
        status = ''
        
        st = organizerRecord.objects.filter(user=request.user)
        for i in st:
            status = i.status
        if status == 'verified':
            try:
                if request.user.is_staff:
                    form = EventForm()
                else:
                    raise PermissionDenied
                return render(request, self.template_name, {'form': form})
            except PermissionDenied:
                messages.error(request, 'Permission Denied')
                return redirect('event:event_list')
        else:
            messages.warning(request, "Your account is not verified.please wait until it verify")
            return redirect('event:event_list')

    def post(self, request):
        try:
            if request.user.is_staff:
                form = EventForm(request.POST, request.FILES)
                if form.is_valid():
                    temp = form.save(commit=False)
                    temp.user = request.user
                    temp.save()
                    messages.success(request, 'Event Added')
                    return redirect('event:event_form',temp.slug)
                else:
                    messages.error(request, 'Invalid Input')
            else:
                raise PermissionDenied
            return render(request, self.template_name, {'form': form,'base':BASE_URL})
        except Exception:
            messages.error(request, 'Permission Denied')
            return redirect('event:event_list')


# noinspection PyBroadException
class UpdateEvent(TemplateView):
    template_name = 'add_update_event.html'

    def get(self, request, *args, **kwargs):
        try:
            if request.user.is_staff or request.user.is_superuser:
                obj = EventRecord.objects.get(slug=kwargs['slug'])
                if obj.user == request.user or request.user.is_superuser:
                    form = EventForm(instance=obj)
                else:
                    raise PermissionDenied
            else:
                raise PermissionDenied
            return render(request, self.template_name, {'form': form})
        except Exception:
            messages.error(request, 'Permission Denied')
            return redirect('event:event_list')

    def post(self, request, **kwargs):
        try:
            obj = EventRecord.objects.get(slug=kwargs['slug'])
            f = obj.fees
            if obj.user == request.user or request.user.is_superuser:
                form = EventForm(request.POST, request.FILES, instance=obj)
                if form.is_valid():
                    fee = form.cleaned_data['fees']
                    diff = fee - f
                    if diff == 0:
                        form.save()
                        messages.success(request, 'Event Updated')
                        
                    else:
                        if obj.event_booked == 0:
                            form.save()
                            messages.success(request, 'Event Updated')
                        else:
                            messages.warning(request, "Event Already Booked.Can't Change The Fee")
                            raise PermissionDenied

event/templates/form/contact.html
{% if formupdate %}
  
{% for form in formupdate %}
  <div class="row mt-4">
    <div class="col-4 col-md-3">
        <label for="{{ form.type.id_for_label }}">{{ form.type.label }}</label>
        {{ form.type }}
    </div>
    <div class="col-4 col-md-3">
        <label for="{{ form.label.id_for_label }}">{{ form.label.label }}</label>
        {{ form.label }}
    </div>
    <input type="hidden" name="{{ form.prefix }}-id" value="{{ form.instance.id }}">
    <div class="col-3 align-self-end">
        <button class="btn btn-danger" type="button" hx-on="click: this.closest('form').remove()">
            Cancel
        </button>
    </div>
</div>
{% endfor %}
{% else %}
<div class="row mt-4">
    <div class="col-4 col-md-3">
        <label for="{{ form.type.id_for_label }}">{{ form.type.label }}</label>
        {{ form.type }}
    </div>
    <div class="col-4 col-md-3">
        <label for="{{ form.label.id_for_label }}">{{ form.label.label }}</label>
        {{ form.label }}
    </div>
    <input type="hidden" name="{{ form.prefix }}-id" value="{{ form.instance.id }}">
    <div class="col-3 align-self-end">
        <button class="btn btn-danger" type="button" hx-on="click: this.closest('form').remove()">
            Cancel
        </button>
    </div>
</div>
{% endif %}

event/templates/form/eventbase.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <script src="https://unpkg.com/hyperscript.org@0.9.5"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/htmx/1.9.3/htmx.min.js" integrity="sha512-+tp2z7fiP5/7Q3DZZkHXaV1BjgtkLuV4vX7khfzKqVJ+/55LWr7Ulz0cqIS1AlB+wmZW6oAkE64VN2sjFXs6dA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>

  <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' hx-target="#contact-list" hx-swap="beforeend">

    <div class="container mt-5">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

event/templates/form/form.html
{% if client %}
  <form method="post"
        hx-post="{% url 'event:update_form' slug %}"
        hx-on="htmx:afterRequest"
        hx-trigger="click from:#submit-all">

        {{ formset.management_form }}
  {% for form in formset %}
  <div class="row mt-4">
    <div class="col-4 col-md-3">
        <label for="{{ form.type.id_for_label }}">{{ form.type.label }}</label>
        {{ form.type }}
    </div>
    <div class="col-4 col-md-3">
        <label for="{{ form.label.id_for_label }}">{{ form.label.label }}</label>
        {{ form.label }}
    </div>
    <input type="hidden" name="{{ form.prefix }}-id" value="{{ form.instance.id }}">
    <div class="col-3 align-self-end">
        <button class="btn btn-danger" type="button" hx-on="click: this.closest('form').remove()">
            Cancel
        </button>
    </div>
</div>
{% endfor %}
  </form>
{% else %}
  <form method="post"
        hx-post="{% url 'event:create_form' slug %}"
        hx-on="htmx:afterRequest"
        hx-trigger="click from:#submit-all">

    <div class="row mt-4">
        <div class="col-4 col-md-3">
            <label for="{{form.type.id_for_label}}">{{ form.type.label }}</label>
            {{form.type}}
        </div>
        <div class="col-4 col-md-3">
            <label for="{{form.label.id_for_label}}">{{ form.label.label }}</label>
            {{form.label}}
        </div>
        <div class="col-3 align-self-end">
            <button class="btn btn-danger" type="button" hx-on="click: this.closest('form').remove()">
                Cancel
            </button>
        </div>
    </div>

  </form>
{% endif %}

<script>
    function nav(){
        
    window.location.href = "{%url 'home'%}";
    alert('submitted successfully')
  };
</script>

event/templates/form/index.html
{% extends 'form/eventbase.html' %}

{% block content %}

<h1 class="mb-4 text-primary">Event form</h1>

<div id="contact-forms">
    {% include "form/form.html " %}
</div>

<div class="my-4">

    <button type="button" 
    class="btn btn-success me-2"
    hx-get="{% url 'event:create_form' slug %}"
    hx-target="#contact-forms"
    hx-swap="beforeend">+ Add Field</button>


    <button 
    type="button" 
    class="btn btn-primary" 
    id="submit-all" 
    onclick='nav()'
    >Submit</button><br>
    


</div>
<ul id="contact-list">
    {% for contact in contacts %}
        {% include "form/contact.html" %}
    {% endfor %}
</ul>

{% if contacts %}
<p>successfully submitted.</p>
{%endif%}
<a href="{% url 'home' %}" class="btn btn-success mt-3">home</a>
{% endblock %}

event/templates/form/test.html
hello