event/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import AddEvent, EventDetail, UpdateEvent, DeleteEvent, EventListView, showform, createform, updateform

urlpatterns = [
    path('', EventListView.as_view(), name='event_list'),
    path('add-event', login_required(AddEvent.as_view()), name='add_event'),
    path('<slug>/event-form/', login_required(showform), name='event_form'),
    path('<slug>/create-form/',login_required(createform), name='create_form'),
    path('<slug>/update-form/',login_required(updateform), name='update_form'),
    path('<slug>/event-detail', EventDetail.as_view(), name='event_detail'),
    path('<slug>/update-event', login_required(UpdateEvent.as_view()), name='update_event'),
    path('<slug>/delete/<timestamp>', login_required(DeleteEvent.as_view()), name='delete_event'),
]

eventlify/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from .router import router

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from .views import *

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_TITLE

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('event/', include(('event.urls', 'event'), namespace='event')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('registration/', include(('registration.urls', 'registration'), namespace='registration')),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('api/',include(router.urls)),


    # path('set', set_user),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registration/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import RegisterEvent, RegisterParticipantList, RegistrationDetail
from .views import EnrollmentReport, RegistrationReport, TransactionReport
from .views import payment_view, payment_success_view,ticket

urlpatterns = [
    path('<slug>/payment/', payment_view, name='payment'),
    path('<slug>/payment/success', payment_success_view, name='payment_success'),
    path('<slug>/ticket/', ticket, name='ticket'), #timestamp/
    path('<slug>/register-event', RegisterEvent.as_view(), name='register_event'),
    path('<slug>/participant-list', login_required(RegisterParticipantList.as_view()), name='participant_list'),
    path('<registration_id>/detail', login_required(RegistrationDetail.as_view()), name='registration_detail'),
    path('<slug>/print-enroll-list', login_required(EnrollmentReport.as_view()), name='print_enroll_list'),
    path('<slug>/print-organizer-list', login_required(RegistrationReport.as_view()), name='print_organizer_list'),
    path('<slug>/print-transaction-list', login_required(TransactionReport.as_view()), name='print_transaction_list'),
]

event/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.utils import timezone
from django.utils.text import slugify

class EventRecord(models.Model):
    slug = models.SlugField(unique=True,null=True,blank=True)
    types = models.CharField(max_length=110, blank=True,default='')
    event_title = models.CharField(max_length=110, null=True, blank=True)
    event_subtitle = models.CharField(max_length=110, null=True, blank=True)
    fees = models.FloatField(default=0)
    about = RichTextUploadingField(null=True, blank=True)
    event_start_date = models.DateField(null=True, blank=True)
    event_end_date = models.DateField(null=True, blank=True)
    event_start_time = models.TimeField(null=True, blank=True) 
    event_end_time = models.TimeField(null=True, blank=True)
    venue = models.CharField(max_length=150, null=True, blank=True)
    state = models.CharField(max_length=150, null=True, blank=True)
    country = models.CharField(max_length=150, null=True, blank=True)
    visibility = models.CharField(max_length=50, null=True, blank=True)
    platform = models.CharField(max_length=50, null=True, blank=True)
    registration_start = models.DateField(null=True, blank=True)
    registration_end = models.DateField(null=True, blank=True)
    no_of_tickets = models.IntegerField(null=True, blank=True)
    category = models.CharField(max_length=50, null=True, blank=True)
    subcategory = models.CharField(max_length=50, null=True, blank=True)
    website = models.CharField(max_length=50, null=True, blank=True)
    facebook = models.CharField(max_length=50, null=True, blank=True)
    instagram = models.CharField(max_length=50, null=True, blank=True)
    youtube = models.CharField(max_length=50, null=True, blank=True)
    poster = models.FileField(default="")
    event_booked = models.IntegerField(default=0)
    registration_open = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    deleted = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.registration_start and self.registration_end:
            now = timezone.now().date()
            if now >= self.registration_start and now <= self.registration_end:
                self.registration_open = True
            else:
                self.registration_open = False

        if not self.slug:
            self.slug = self.get_unique_slug(self.event_title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.event_title

    def get_unique_slug(self, title):
        timestamp = timezone.now().strftime('%Y%m%d%H%M%S')
        slug = slugify(f"{title}-{timestamp}")
        unique_slug = slug
        num = 1
        while EventRecord.objects.filter(slug=unique_slug).exists():
            unique_slug = f"{slug}-{num}"
            num += 1
        return unique_slug




OPTION = [
    ('text', 'Text'),
    ('number', 'Number'),
    ('email', 'Email'),
    ('textarea', 'Textarea')
]


class Client(models.Model):
    event = models.ForeignKey(EventRecord, on_delete=models.CASCADE)
    label = models.CharField(max_length=200,null=True)
    type = models.CharField(max_length=20, choices=OPTION,null=True)
    organizer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    

    def __str__(self):
        return self.label


class Answer(models.Model):
    email = models.EmailField(default='')
    event = models.ForeignKey(EventRecord, null=True, on_delete=models.CASCADE, blank=True)
    question = models.ForeignKey(Client, null=True, on_delete=models.CASCADE)
    response = models.CharField(max_length=200,null=True)

    def __str__(self):
            return self.email

class DataList(models.Model):
    place = models.CharField(max_length=50)
    number = models.IntegerField()

    def __str__(self):
        return self.place

event/views.py
from datetime import date
from django.db.models import Q

from django.contrib import messages
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.forms import modelformset_factory
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import TemplateView
from organizer.models import organizerRecord
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseRedirect


from registration.models import RegistrationRecord
from .forms import AnswerForm, EventForm,ClientForm
from .models import Answer, EventRecord,Client
from eventlify.settings import BASE_URL



def createform(request,*args, **kwargs):
    if(request.method == "POST"):
        form = ClientForm(request.POST)
        obj = EventRecord.objects.get(slug=kwargs['slug'])
        if form.is_valid():
            temp = form.save(commit=False)
            temp.organizer = request.user
            temp.event = obj
            temp.save()
            
            messages.success(request, 'Submitted Successfully')
            context = {"form": temp}
            return render(request, "form/contact.html",context)
    
    else:
        try:
            obj = EventRecord.objects.get(slug=kwargs['slug'])
            form = ClientForm()
            context = {'form': form,'slug':obj.slug}
            return render(request, "form/form.html", context)
        except Exception:
            return redirect('event:event_list')
        


def answerform(request,*args, **kwargs):
    if(request.method == "POST"):
        form = AnswerForm(request.POST)
        obj = EventRecord.objects.get(slug=kwargs['slug'])
        if form.is_valid():
            temp = form.save(commit=False)
            temp.user = request.user
            temp.event = obj
            temp.save()
            messages.success(request, 'Submitted Successfully')
            context = {"contact": temp}
            return render(request, "form/contact.html",context)
    
    else:
        try:
            obj = EventRecord.objects.get(slug=kwargs['slug'])
            form = AnswerForm()
            context = {'form': form,'slug':obj.slug}
            return render(request, "form/form.html", context)
        except Exception:
            return redirect('event:event_list')
        

def updateform(request, *args, **kwargs):
    obj = get_object_or_404(EventRecord, slug=kwargs['slug'])
    clt_queryset = Client.objects.filter(event=obj)
    
    if request.method == "POST":
        ClientFormSet = modelformset_factory(Client, form=ClientForm, extra=0)
        formset = ClientFormSet(request.POST, queryset=clt_queryset)
        if formset.is_valid():
            formset.save()
            messages.success(request, 'Form Updated')
            context = {"formupdate": formset}
            return render(request, "form/contact.html", context)
        else:
            messages.error(request, 'Invalid Input')
    else:
        formset = ClientForm()

    context = {'formset': formset, 'slug': obj.slug}
    return render(request, "form/form.html", context)


def showform(request, *args, **kwargs):
    obj = EventRecord.objects.get(slug=kwargs['slug'])
    clt = Client.objects.filter(event=obj)
    
    if clt:
        ClientFormSet = modelformset_factory(Client, form=ClientForm, extra=0)
        formset = ClientFormSet(queryset=clt)
    else:
        formset = ClientForm()
    
    context = {'formset': formset, 'slug': obj.slug, 'client': clt}
    return render(request, "form/index.html", context)

    

# Create your views here.
class EventListView(TemplateView):
    template_name = 'event-list.html'

    def get(self, request, *args, **kwargs):
        request.session['head_name'] = 'event'
        event_list = EventRecord.objects.all().order_by('-event_start_date')
        form = EventForm()
        category = request.GET.get('category')
        platform = request.GET.get('platform')
        search_query = request.GET.get('search')
        if search_query:
            event_list = event_list.filter(
                Q(event_title__icontains=search_query) |
                Q(about__icontains=search_query)
            )

        # Apply category filter if parameter is provided
        if category != None:
            event_list = event_list.filter(category=category)
        if platform != None:
            event_list = event_list.filter(platform=platform)
        
        now = date.today()
        for i in event_list:
            if not now <= i.registration_end:
                i.registration_open = False
                i.save(update_fields=['registration_open'])

        return render(request, self.template_name, {'event_list': event_list,'form': form})


# noinspection PyBroadException
class EventDetail(TemplateView):
    template_name = 'event_detail.html'

    def get(self, request, *args, **kwargs):
        try:
            owner = False
            registered = True
            obj = EventRecord.objects.get(slug=kwargs['slug'])
            base_url = BASE_URL
            
            if obj.user == request.user or request.user.is_superuser:
                owner = True
            else:
                try:
                    RegistrationRecord.objects.get(user=request.user, event=obj)
                except Exception:
                    registered = False
            print(obj.event_booked)
            return render(request, self.template_name,
                          {'obj': obj, 
                           'owner': owner, 
                           'registered': registered, 
                           'now': date.today(),
                           'base':base_url})
        except ObjectDoesNotExist:
            messages.error(request, 'Event Not found')
            return redirect('event:event_list')


    # def post(self, request):
    #     if True:
    #         if request.user.is_staff:
    #             form = EventForm(request.POST, request.FILES)
    #             if form.is_valid():
    #                 temp = form.save(commit=False)
    #                 temp.user = request.user
    #                 form.save()
    #                 messages.success(request, 'Event Added')
    #                 return redirect('event:event_detail', slug=temp.slug)
    #             else:
    #                 messages.error(request, 'Invalid Input')
    #         else:
    #             raise PermissionDenied
    #         return render(request, self.template_name, {'form': form,'base':BASE_URL})
    
# noinspection PyBroadException
class AddEvent(TemplateView):
    template_name = 'add_update_event.html'
    def get(self, request, *args, **kwargs):
        request.session['head_name'] = 'add_event'
        
        status = ''
        
        st = organizerRecord.objects.filter(user=request.user)
        for i in st:
            status = i.status
        if status == 'verified':
            try:
                if request.user.is_staff:
                    form = EventForm()
                else:
                    raise PermissionDenied
                return render(request, self.template_name, {'form': form})
            except PermissionDenied:
                messages.error(request, 'Permission Denied')
                return redirect('event:event_list')
        else:
            messages.warning(request, "Your account is not verified.please wait until it verify")
            return redirect('event:event_list')

    def post(self, request):
        try:
            if request.user.is_staff:
                form = EventForm(request.POST, request.FILES)
                if form.is_valid():
                    temp = form.save(commit=False)
                    temp.user = request.user
                    temp.save()
                    messages.success(request, 'Event Added')
                    return redirect('event:event_form',temp.slug)
                else:
                    messages.error(request, 'Invalid Input')
            else:
                raise PermissionDenied
            return render(request, self.template_name, {'form': form,'base':BASE_URL})
        except Exception:
            messages.error(request, 'Permission Denied')
            return redirect('event:event_list')


# noinspection PyBroadException
class UpdateEvent(TemplateView):
    template_name = 'add_update_event.html'

    def get(self, request, *args, **kwargs):
        try:
            if request.user.is_staff or request.user.is_superuser:
                obj = EventRecord.objects.get(slug=kwargs['slug'])
                if obj.user == request.user or request.user.is_superuser:
                    form = EventForm(instance=obj)
                else:
                    raise PermissionDenied
            else:
                raise PermissionDenied
            return render(request, self.template_name, {'form': form})
        except Exception:
            messages.error(request, 'Permission Denied')
            return redirect('event:event_list')

    def post(self, request, **kwargs):
        try:
            obj = EventRecord.objects.get(slug=kwargs['slug'])
            f = obj.fees
            if obj.user == request.user or request.user.is_superuser:
                form = EventForm(request.POST, request.FILES, instance=obj)
                if form.is_valid():
                    fee = form.cleaned_data['fees']
                    diff = fee - f
                    if diff == 0:
                        form.save()
                        messages.success(request, 'Event Updated')
                        
                    else:
                        if obj.event_booked == 0:
                            form.save()
                            messages.success(request, 'Event Updated')
                        else:
                            messages.warning(request, "Event Already Booked.Can't Change The Fee")
                            raise PermissionDenied

event/templates/add_update_event.html
{% extends "base.html" %}{% load staticfiles %}{% block head_title %}Add Event | {{ block.super }}{% endblock %}
{% block content %}
    <div class="p-3 pt-4 bg-white rounded shadow-sm">
        <h2>Add/Update Event</h2>
        <form enctype="multipart/form-data" action="" method="post" class="px-md-2">{% csrf_token %}
            <h3>Event Information*</h3>
            <div class="form-row px-md-5">
                {{ form.media }}
                
                
                
                <div class="pb-4 col-md-8"><label>Event Title</label>{{ form.event_title }}{{ form.event_title.errors }}</div>
                
                <div class="pb-4 col-md-8"><label>Event Subtitle</label>{{ form.event_subtitle }}{{ form.event_subtitle.errors }}</div>
                
                <div class="pb-4 col-md-4"><label>Fees</label>{{ form.fees }}{{ form.fees.errors }}</div>
                
                <div class="pb-4 col-md-12"><label>about</label><br>{{ form.about }}{{ form.about.errors }}</div>
                
                <div class="pb-4 col-md-4"><label>Type</label>{{ form.types }}{{ form.types.errors }}</div>

                <div class="pb-4 col-md-4">
                    <label>Event start date</label>{{ form.event_start_date }}{{ form.event_start_date.errors }}
                </div>

                <div class="pb-4 col-md-4">
                    <label>Event end date</label>{{ form.event_end_date }}{{ form.event_end_date.errors }}
                </div>

                <div class="pb-4 col-md-4">
                    <label>Event start time</label>{{ form.event_start_time }}{{ form.event_start_time.errors }}
                </div>
                
                <div class="pb-4 col-md-4">
                    <label>Event end time</label>{{ form.event_end_time }}{{ form.event_end_time.errors }}
                </div>
                <div class="pb-4 col-md-4"><label>Mode of event</label>{{ form.visibility }}{{ form.visibility.errors }}</div>
                
                <div class="pb-4 col-md-4"><label>Platform of event</label>{{ form.platform }}{{ form.platform.errors }}</div>
                
                <div class="pb-4 col-md-8"><label>Venue</label>{{ form.venue|safe }}{{ form.venue.errors }}</div>
                <div class="pb-4 col-md-4"><label>State</label>{{ form.state }}{{ form.venue.errors }}</div>
                <div class="pb-4 col-md-4"><label>Country</label>{{ form.country|safe }}{{ form.venue.errors }}</div>

                


                <div class="pb-4 col-md-4">
                    <label>Registration start</label>{{ form.registration_start }}{{ form.registration_start.errors }}
                </div>

                <div class="pb-4 col-md-4">
                    <label>Registration end</label>{{ form.registration_end }}{{ form.registration_end.errors }}
                </div>


                <div class="pb-4 col-md-4">
                    <label>No of tickets</label>{{ form.no_of_tickets }}{{ form.no_of_tickets.errors }}
                </div>


                <div class="pb-4 col-md-4"><label>Category</label>{{ form.category }}{{ form.category.errors }}</div>

                <div class="pb-4 col-md-4"><label>Subcategory</label>{{ form.subcategory }}{{ form.subcategory.errors }}</div>

                <div class="pb-4 col-md-4"><label>Website Link</label>{{ form.website }}{{ form.website.errors }}</div>
                <div class="pb-4 col-md-4"><label>Facebook Link</label>{{ form.facebook }}{{ form.facebook.errors }}</div>
                <div class="pb-4 col-md-4"><label>Instagram Link</label>{{ form.instagram }}{{ form.instagram.errors }}</div>
                <div class="pb-4 col-md-4"><label>Youtube Link</label>{{ form.youtube }}{{ form.youtube.errors }}</div>

                <div class="pb-4 col-md-4"><label>Event Poster: (100X100 svg file)</label>{{ form.poster }}{{ form.poster.errors }}</div>
                
            </div>
            <div class="px-md-5 pb-5 btn-toolbar">
                <button type="submit" class="px-5 m-2 btn btn-outline-primary">Submit</button>
                <button type="reset" class="px-4 m-2 btn btn-outline-danger">Reset</button>
            </div>
        </form>
    </div>
    
    {% endblock %}

event/templates/event_detail.html
{% extends 'base.html' %}{% load staticfiles %}{% block head_title %}Event
Detail | {{ block.super }}{% endblock %}
<main>{% block content %}
    <style>
      .img {
        background-size: contain;

        height: 350px;
      }

      h1 {
        font-size: 40px;
        font-weight: bold;
      }

      h4 {
        
        font-weight: bold;

      }

      h5 {
        font-size: 20px;
      }

      h6 {
        font-size: 17px;
      }
      
      .img-blur-wrap {
        position:relative;
        overflow:hidden;
      }
      .img-blur {
          background:url(./assets/images/poster.jpg) center no-repeat;
          background-size:auto,cover;
          filter: none;
          z-index: 2;
          position: relative;
          max-width: 40rem;
          height:40rem;
          margin: 0 auto;  
          box-shadow:0px 20px 40px #000;
      }
      .img-blur-bg {
        background:linear-gradient(rgba(0, 0, 0, 0.3),rgba(0, 0, 0, 0.3) ),  url(./assets/images/poster.jpg) center no-repeat;
        background-size:auto,cover;
        filter: blur(5px);
        width:100%;
        height:40rem;
        position: absolute;
        z-index: 1;
      }
      
    </style>

    <section class="container">
      <div class='img-blur-wrap mb-5' >
        <div class='img-blur-bg' style="background:linear-gradient(rgba(0, 0, 0, 0.3),rgba(0, 0, 0, 0.3) ),  url('{{ base }}/media/{{ obj.poster }}') center no-repeat;"></div>
        <div class='img-blur' style="background:url('{{ base }}/media/{{ obj.poster }}') center no-repeat;"></div>
      </div>
    <div class="row">
      <div class="col">
        
        <h5>{{obj.event_start_date}}</h5>
        <h1>{{ obj.event_title|upper }}</h1>
        <h6>{{ obj.event_subtitle|upper }}</h6>
      </div>

      <div class="card text-center" style="width: 30rem;color: #000;">
        {% if owner %}
        <div class="card-body"> 
          <a
          class="btn btn-custom mb-4 w-100"
          href="{% url 'event:update_event' obj.slug %}"
          >Update</a>
        </div>
        {% elif registered %}
        <div class="card-body">
          <button
          class="btn btn-custom mb-4"
          disabled
        >
          Already Registered
        </button>
        </div>
        
        {% else %}
        


        {% if now <= obj.registration_end and obj.registration_open %}


                  {% if obj.no_of_tickets <= obj.event_booked %}
                  <div class="card-body">
                    <button
                    class="btn btn-custom mb-4"
                    disabled
                  >
                    Registration Full</button>
                    <p style="border-style: solid;
                  border-width: medium;border-color: #1492E6;">EVENTID : EVTLY0{{obj.id}}</p>
                  </div>
                  {%else%}
              <div class="card-body">
                <h5 class="card-title">Tickets</h5>
                <div class="">
                    <a class="btn btn-custom" href="javascript:void(0);" onclick="decrementQuantity();" style="width: 2rem">-</a>
                    <span id="quantity">1</span>
                    <a class="btn btn-custom" href="javascript:void(0);" onclick="incrementQuantity();" style="width: 2rem">+</a>
                </div>
                {% if obj.fees == 0 %}
                  <p class="card-text">Free</p>
                {% else %}
                  <p class="card-text">₹{{ obj.fees }}</p>
                {% endif %}
                <hr />
                <a class="btn btn-custom mb-4 w-100"
                  onclick='return confirm("Are you sure to register in {{ obj.event_name }}")'
                  href="{% url 'registration:payment' obj.slug %}?quantity=" id="register-link">Register Now</a>
                <p style="border-style: solid; border-width: medium; border-color: #1492E6;">EVENTID : EVTLY0{{ obj.id }}</p>
            </div>
            {%endif%}
      
        {% else %}
        <div class="card-body">
          <button
          class="btn btn-custom mb-4"
          disabled
        >
          Registration Closed</button>
          <p style="border-style: solid;
        border-width: medium;border-color: #1492E6;">EVENTID : EVTLY0{{obj.id}}</p>
        </div>
        {% endif %}
        {% endif %}

        
      </div>
    </div>

    <div style="display:block;width:100%;">
    <h4 class="row" style="display:block;">When and Where</h4>
    <div class="row">
      <div class="col-4 ml-4">
        <h5>Date and Time</h5>
        <p>{{obj.event_start_date}}-{{obj.event_end_date}} <br>{{obj.event_start_time}}-{{obj.event_end_time}}</p>
      </div>
      <div class="col-4">
        <h5>Location</h5>
        <p>{{obj.venue|safe}}</p>
      </div>
    </div>
  </div>
    <div class="">
      <h4>About</h4>
      <p class="ml-4">
        {{obj.about|safe}}
      </p>
    </div>
    
  </section>

  <script>
    let currentQuantity = 1;

    function updateQuantity() {
        const quantityElement = document.getElementById('quantity');
        quantityElement.innerText = currentQuantity;
        const registerLink = document.getElementById('register-link');
        registerLink.href = `{% url 'registration:payment' obj.slug %}?quantity=${currentQuantity}`;
    }

    function incrementQuantity() {
        currentQuantity++;
        updateQuantity();
    }

    function decrementQuantity() {
        if (currentQuantity > 1) {
            currentQuantity--;
            updateQuantity();
        }
    }

    // Initial update
    updateQuantity();
</script>




{% endblock content %}