account/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import superuser, del_user, edit_user, accept_organizer, reject_organizer
from .views import logout, Login, Signup, ForgetPassword, Activate, ConsolidatedView,contactus

urlpatterns = [
    path('login', Login.as_view(), name='login'),
    path('signup', Signup.as_view(), name='signup'),
    path('contact', contactus, name='contactus'),
    path('logout', login_required(logout), name='logout'),
    path('activate/<uidb64>/<token>/', Activate.as_view(), name='activate'),
    path('forget-password/<uidb64>/<token>', ForgetPassword.as_view(), name='forget_password'),

    path('superuser/', login_required(superuser), name='superuser'),
    path('edit_user/<username>', login_required(edit_user), name='edit_user'),
    path('delete-user/<username>', login_required(del_user), name='delete_user'),

    path('consolidated-view-all', login_required(ConsolidatedView.as_view()), name='consolidated_view_all'),
    path('consolidated-view-username/<username>', login_required(ConsolidatedView.as_view()), name='consolidated_username'),
    path('accept_organizer/<int:id>/', accept_organizer, name='accept_organizer'),
    path('reject_organizer/<int:id>/', reject_organizer, name='reject_organizer'),
]

event/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import AddEvent, EventDetail, UpdateEvent, DeleteEvent, EventListView, showform, createform, updateform

urlpatterns = [
    path('', EventListView.as_view(), name='event_list'),
    path('add-event', login_required(AddEvent.as_view()), name='add_event'),
    path('<slug>/event-form/', login_required(showform), name='event_form'),
    path('<slug>/create-form/',login_required(createform), name='create_form'),
    path('<slug>/update-form/',login_required(updateform), name='update_form'),
    path('<slug>/event-detail', EventDetail.as_view(), name='event_detail'),
    path('<slug>/update-event', login_required(UpdateEvent.as_view()), name='update_event'),
    path('<slug>/delete/<timestamp>', login_required(DeleteEvent.as_view()), name='delete_event'),
]

eventlify/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from .router import router

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from .views import *

admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_TITLE

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('event/', include(('event.urls', 'event'), namespace='event')),
    path('account/', include(('account.urls', 'account'), namespace='account')),
    path('registration/', include(('registration.urls', 'registration'), namespace='registration')),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('api/',include(router.urls)),


    # path('set', set_user),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>{% load static from staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>{% block head_title %}eventlify Event{% endblock head_title %}</title>
    <style>
      #loading {
        position: fixed;
        width: 100%;
        height: 100%;
        background: #fff url("{% static 'images/Bulb.gif' %}") no-repeat center;
        z-index: 99999;
      }
    </style>
    <link rel="shortcut icon" href="{% static 'favicon.png' %}" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
      integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="//fonts.googleapis.com/css?family=Varela+Round"
    />
    <script src="https://unpkg.com/hyperscript.org@0.9.5"></script>
    <script src="https://unpkg.com/htmx.org@1.9.2"></script>
    <
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js" integrity="sha512-fD9DI5bZwQxOi7MhYWnnNPlvXdp/2Pj3XSTRrFs5FQa4mizyGLnJcN6tuvUS6LbmgN1ut+XGSABKvjN0H6Aoow==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    {% block css %}{% endblock css %}
  </head>
  <body onload="preloader()" style="min-height: 100%">
    <div id="loading" about="preloader"></div>
    <nav
      class="navbar navbar-expand-lg navbar-light fixed-top"
      style="
        padding: 0;
        box-shadow: 0 0.15rem 0.1rem 0 rgba(0, 0, 0, 0.05);
        background-color: white;
      "
    >
      <a class="navbar-brand p-0" href="{% url 'home' %}"
        ><img
          src="{% static 'images/eventlifylogo.png' %}"
          style="width: 10rem; padding-left: 1rem;height: 4rem;"
          alt="eventlify"
      /></a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <div class="flex-grow-1 flex-column">
          <div
            class="my-3 my-md-3 mr-md-5 align-items-md-center text-center text-md-right"
          >
            <a
              class="py-1 mr-md-5 ml-2 custom-a {% if request.session.head_name == 'home' %}under-line{% endif %}"
              href="{% url 'home' %}"
              >Home</a
            >
            
          
            {% if user.is_authenticated %} {% if user.is_superuser %}
            <a
              class="py-1 mr-md-5 ml-2 custom-a {% if request.session.head_name == 'manage_user' %}under-line{% endif %}"
              href="{% url 'account:superuser' %}"
              >Manage Request</a
            >
            
            {% elif user.is_staff %}
            <a
              class="py-1 mr-md-5 ml-2 custom-a {% if request.session.head_name == 'event' %}under-line{% endif %}"
              href="{% url 'event:event_list' %}"
              >Event</a
            >
            <a
              class="py-1 mr-md-5 ml-2 custom-a {% if request.session.head_name == 'add_event' %}under-line{% endif %}"
              href="{% url 'event:add_event' %}"
              >Add Event</a
            >{% endif %}
            <a
              class="py-1 mr-md-5 ml-2 custom-a {% if request.session.head_name == 'profile' %}under-line{% endif %}"
              href="{% url 'account:consolidated_view_all' %}"
              >Consolidated View</a
            >
            <a
              class="py-1 mr-md-5 ml-2 custom-a"
              href="{% url 'account:logout' %}"
              >Logout</a
            >
            {% else %}
            <a
              class="py-1 mr-md-5 ml-2 custom-a {% if request.session.head_name == 'event' %}under-line{% endif %}"
              href="{% url 'event:event_list' %}"
              >Event</a
            >
            
            <a
              class="py-1 ml-2 custom-a {% if request.session.head_name == 'signup' %}under-line{% endif %}"
              href="{% url 'account:signup' %}"
              >Organizer</a
            >
            <a
              class="py-1 ml-2 custom-a {% if request.session.head_name == 'contactus' %}under-line{% endif %}"
              href="{% url 'account:contactus' %}"
              >Contact Us</a
            >
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <div class="pt-2 mt-2 pt-md-5 mt-md-5">
      {% for m in messages %}
      <!-- Alert -->
      <div
        class="alert alert-dismissible fade show container fit-text mt-4 {% if m.tags == 'success' %}alert-success{% elif m.tags == 'warning' %}alert-warning{% elif m.tags == 'info' %}alert-info{% else %}alert-danger{% endif %}"
        role="alert"
      >
        {{ m }}
        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      <!-- - - - - - - - - - START - - - - - - - - - - - -->
      {% block content%}{% endblock content %}
      <!-- - - - - - - - - - END - - - - - - - - - - - - -->
    </div>
    
    
    <!-- Preloader Scripts -->
    <script>
      function preloader() {
        document.getElementById("loading").style.display = "none";
      }
    </script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
      integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
      integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js/search.js' %}"></script>
    {% block script %}{% endblock script %}
  </body>

</html>

templates/index.html
{% extends "base.html" %}{% load staticfiles %}{% block head_title %}Home{% endblock %}
{% block content %}
    <div class="row" style="margin: 1rem 0 0 0">
        <div class="col-lg-6 order-lg-1 pb-5">
            <img src="{% static 'images/Asset 50.svg' %}" alt="logo" style="width: 100%"></div>
        <div class="col-lg-6 order-lg-0 align-self-lg-center px-lg-5 pb-5 text-center">
            <h1 class="px-4" style="color:#414141;font-size: 3rem;">Eventlify</h1>
            <hr style="width: 70px; border: 1px solid rgba(0,0,0,0.23);">
            <p class="px-3" style="font-size: 24px; color:#777777;">A gateway to book events</p>
           
            <a class="btn btn-custom mt-4 px-lg-5 py-3" href="{% url 'event:event_list' %}" style="border: 0; font-size: 24px; box-shadow: 5px 5px 10px rgba(0,0,0,.50)!important;">Book your events</a><br><br>
            
        </div>
    </div>
    
    
{% endblock %}